include_guard(GLOBAL)

set(PYRXTOOLS_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB PYRXTOOLS_SOURCES
	${PYRXTOOLS_DIR}/src/*.hpp
	${PYRXTOOLS_DIR}/src/*.cpp)

include("${PYRXTOOLS_DIR}/src/rxtools/rxtools.cmake")

set(PYRXTOOLS_EXTERNAL_INCLUDES
	${RXTOOLS_INCLUDES}
	)

set(PYRXTOOLS_EXTERNAL_LINKS
	${RXTOOLS_LINKS}
	)

set(PYRXTOOLS_INCLUDES
	${PYRXTOOLS_EXTERNAL_INCLUDES}
	${PYRXTOOLS_DIR}/src
	)
set(PYRXTOOLS_LINKS
	${PYRXTOOLS_EXTERNAL_LINKS}
	pyRxTools
	)
